package com.firesms.app.domain.rules

import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/** The subset of parser-rule fields that can be generated by an LLM and imported. */
data class ImportedRuleFields(
    val bodyPattern: String,
    val amountTemplate: String,
    val descriptionSource: String,
    val descriptionValue: String,
    val type: String,
    val datePattern: String,
    val dateFormat: String,
    val remarksPattern: String,
    val remarksTemplate: String
)

sealed interface RuleJsonImportResult {
    data class Success(
        val fields: ImportedRuleFields,
        val repairedInvalidEscapes: Boolean = false
    ) : RuleJsonImportResult

    data class Error(val message: String) : RuleJsonImportResult
}

private data class RuleJsonPayload(
    val bodyPattern: String,
    val amountTemplate: String,
    val descriptionSource: String,
    val descriptionValue: String,
    val type: String,
    val datePattern: String? = null,
    val dateFormat: String? = null,
    val remarksPattern: String? = null,
    val remarksTemplate: String? = null
)

object RuleJsonImporter {

    fun parse(input: String): RuleJsonImportResult {
        val normalized = stripMarkdownFence(input)
        if (normalized.isBlank()) {
            return RuleJsonImportResult.Error("Paste the rule JSON first.")
        }
        val repairedInput = repairInvalidJsonEscapes(normalized)

        val payload = try {
            decodePayload(repairedInput.value)
        } catch (e: SerializationException) {
            return RuleJsonImportResult.Error(
                "Invalid rule JSON. Check that all required fields are present and properly escaped."
            )
        } catch (e: Exception) {
            return RuleJsonImportResult.Error("Invalid rule JSON: ${e.message ?: "unable to read input"}")
        }

        if (payload.bodyPattern.isBlank()) {
            return RuleJsonImportResult.Error("bodyPattern cannot be blank.")
        }
        try {
            Regex(payload.bodyPattern, RegexOption.DOT_MATCHES_ALL)
        } catch (_: IllegalArgumentException) {
            return RuleJsonImportResult.Error("bodyPattern is not a valid Kotlin/Java regular expression.")
        }

        if (payload.amountTemplate.isBlank()) {
            return RuleJsonImportResult.Error("amountTemplate cannot be blank.")
        }
        if (payload.descriptionSource !in setOf("template", "regex_group")) {
            return RuleJsonImportResult.Error(
                "descriptionSource must be either \"template\" or \"regex_group\"."
            )
        }
        if (payload.descriptionValue.isBlank()) {
            return RuleJsonImportResult.Error("descriptionValue cannot be blank.")
        }
        if (payload.type !in setOf("withdrawal", "deposit", "transfer")) {
            return RuleJsonImportResult.Error(
                "type must be \"withdrawal\", \"deposit\", or \"transfer\"."
            )
        }

        val namedGroups = extractNamedGroups(payload.bodyPattern)

        validateTemplate("amountTemplate", payload.amountTemplate, namedGroups)?.let {
            return RuleJsonImportResult.Error(it)
        }
        if (payload.descriptionSource == "regex_group") {
            if (payload.descriptionValue !in namedGroups) {
                return RuleJsonImportResult.Error(
                    "descriptionValue references a group that is missing from bodyPattern."
                )
            }
        } else {
            validateTemplate("descriptionValue", payload.descriptionValue, namedGroups)?.let {
                return RuleJsonImportResult.Error(it)
            }
        }

        val datePattern = payload.datePattern.orEmpty()
        val dateFormat = payload.dateFormat.orEmpty()
        if (datePattern.isBlank() != dateFormat.isBlank()) {
            return RuleJsonImportResult.Error(
                "datePattern and dateFormat must either both be set or both be blank."
            )
        }
        validateOptionalPattern("datePattern", datePattern, namedGroups)?.let {
            return RuleJsonImportResult.Error(it)
        }

        val remarksPattern = payload.remarksPattern.orEmpty()
        val remarksTemplate = payload.remarksTemplate.orEmpty()
        validateOptionalPattern("remarksPattern", remarksPattern, namedGroups)?.let {
            return RuleJsonImportResult.Error(it)
        }
        validateTemplate("remarksTemplate", remarksTemplate, namedGroups)?.let {
            return RuleJsonImportResult.Error(it)
        }

        return RuleJsonImportResult.Success(
            fields = ImportedRuleFields(
                bodyPattern = payload.bodyPattern,
                amountTemplate = payload.amountTemplate,
                descriptionSource = payload.descriptionSource,
                descriptionValue = payload.descriptionValue,
                type = payload.type,
                datePattern = datePattern,
                dateFormat = dateFormat,
                remarksPattern = remarksPattern,
                remarksTemplate = remarksTemplate
            ),
            repairedInvalidEscapes = repairedInput.repaired
        )
    }

    private fun decodePayload(input: String): RuleJsonPayload {
        val jsonObject = Json.parseToJsonElement(input) as? JsonObject
            ?: throw IllegalArgumentException("The imported JSON must be an object.")

        fun requiredString(name: String): String {
            val value = jsonObject[name]
                ?: throw IllegalArgumentException("Missing required field: $name")
            return (value as? JsonPrimitive)
                ?.takeIf { it.isString }
                ?.content
                ?: throw IllegalArgumentException("$name must be a JSON string.")
        }

        fun optionalString(name: String): String? {
            val value = jsonObject[name] ?: return null
            if (value === JsonNull) return null
            return (value as? JsonPrimitive)
                ?.takeIf { it.isString }
                ?.content
                ?: throw IllegalArgumentException("$name must be a JSON string or null.")
        }

        return RuleJsonPayload(
            bodyPattern = requiredString("bodyPattern"),
            amountTemplate = requiredString("amountTemplate"),
            descriptionSource = requiredString("descriptionSource"),
            descriptionValue = requiredString("descriptionValue"),
            type = requiredString("type"),
            datePattern = optionalString("datePattern"),
            dateFormat = optionalString("dateFormat"),
            remarksPattern = optionalString("remarksPattern"),
            remarksTemplate = optionalString("remarksTemplate")
        )
    }

    private fun extractNamedGroups(pattern: String): Set<String> {
        val groups = mutableSetOf<String>()
        var cursor = 0
        while (cursor < pattern.length) {
            val start = pattern.indexOf("(?<", cursor)
            if (start == -1) break
            val nameStart = start + 3
            val nameEnd = pattern.indexOf('>', nameStart)
            if (nameEnd == -1) break
            val name = pattern.substring(nameStart, nameEnd)
            if (name.isNotEmpty() && name.first().isLetter() && name.all { it.isLetterOrDigit() }) {
                groups += name
            }
            cursor = nameEnd + 1
        }
        return groups
    }

    private fun extractPlaceholderNames(template: String): List<String> {
        val groups = mutableListOf<String>()
        var cursor = 0
        while (cursor < template.length) {
            val start = template.indexOf("{{", cursor)
            if (start == -1) break
            val end = template.indexOf("}}", start + 2)
            if (end == -1) break
            val content = template.substring(start + 2, end)
            val name = content.takeWhile { it.isLetterOrDigit() || it == '_' }
            if (name.isNotEmpty()) groups += name
            cursor = end + 2
        }
        return groups
    }

    private fun exactPlaceholderName(pattern: String): String? {
        if (!pattern.startsWith("{{") || !pattern.endsWith("}}")) return null
        val name = pattern.substring(2, pattern.length - 2)
        return name.takeIf {
            it.isNotEmpty() && it.all { char -> char.isLetterOrDigit() || char == '_' }
        }
    }

    private fun validateTemplate(
        fieldName: String,
        template: String,
        namedGroups: Set<String>
    ): String? {
        val missingGroup = extractPlaceholderNames(template)
            .firstOrNull { it !in namedGroups }
        return missingGroup?.let {
            "$fieldName references {{$it}}, which is missing from bodyPattern."
        }
    }

    private fun validateOptionalPattern(
        fieldName: String,
        pattern: String,
        namedGroups: Set<String>
    ): String? {
        if (pattern.isBlank()) return null

        val placeholderName = exactPlaceholderName(pattern)
        if (placeholderName != null) {
            return if (placeholderName in namedGroups) null
            else "$fieldName references {{$placeholderName}}, which is missing from bodyPattern."
        }

        return try {
            Regex(pattern)
            null
        } catch (_: IllegalArgumentException) {
            "$fieldName is not a valid Kotlin/Java regular expression."
        }
    }

    private data class RepairedJsonInput(
        val value: String,
        val repaired: Boolean
    )

    /**
     * LLMs commonly emit regex escapes such as \s in otherwise valid JSON. JSON only accepts
     * a small escape set, so insert the missing escape backslash while leaving valid JSON
     * escapes (including newlines, quotes, Unicode escapes, and already doubled slashes) intact.
     */
    private fun repairInvalidJsonEscapes(input: String): RepairedJsonInput {
        val output = StringBuilder(input.length)
        var insideString = false
        var repaired = false
        var index = 0

        while (index < input.length) {
            val char = input[index]
            if (!insideString) {
                output.append(char)
                if (char == '"') insideString = true
                index++
                continue
            }

            when (char) {
                '"' -> {
                    output.append(char)
                    insideString = false
                    index++
                }
                '\\' -> {
                    if (index + 1 >= input.length) {
                        output.append(char)
                        index++
                        continue
                    }

                    val escaped = input[index + 1]
                    if (escaped in setOf('"', '\\', '/', 'b', 'f', 'n', 'r', 't', 'u')) {
                        output.append(char).append(escaped)
                    } else {
                        output.append("\\\\").append(escaped)
                        repaired = true
                    }
                    index += 2
                }
                else -> {
                    output.append(char)
                    index++
                }
            }
        }

        return RepairedJsonInput(output.toString(), repaired)
    }

    private fun stripMarkdownFence(input: String): String {
        val trimmed = input.trim()
        if (!trimmed.startsWith("```")) return trimmed

        val firstLineEnd = trimmed.indexOf('\n')
        if (firstLineEnd == -1) return trimmed

        val closingFence = trimmed.lastIndexOf("```")
        if (closingFence <= firstLineEnd) return trimmed

        return trimmed.substring(firstLineEnd + 1, closingFence).trim()
    }
}
